---
title: "BA 820 - Group Project"
author: Zhaoying Chen (zychen96), Hui Jiang (hjiang97), Yiying Wang (wangy97), Rui
  Xu (xurr), Tyler Mcmurray (tfm), Yanyue Fu (yanyuefu)
date: "12/6/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(factoextra)
library(corrplot)
library(psych)
library(GPArotation)


bank <- read_csv(file = "bankdata_cleaned.csv")
bank_term_deposit <- bank %>% select(deposit)
data <- bank %>% select(., -job, -marital, -deposit)
```

# Who Are We & What Are We Doing?
Our group works for a finanical services company. We have colected data on our customers. Our data is basic information of demographics including variables like age, marital status, job, and education. We also have information regarding their relationship to the bank like there balance at the bank and loan status if they have some or not. Finally, we have information related to our last marketing campaign where the end goal was to have them open up a term deposit. There are multiple uses with this dataset. We can gain insight and benefits through multiple analysises that we will conduct. We will utilize explatory data analysis, cluster analysis, and supervized learning to benefit our company. 

# About Our Data
As discussed above we have multiple different variables we want to utilize in our analysis. Some of the variables are categorical variables but unfortunately some of the methods we want to utilize requires only using numerical variablles; instead of deleting useful information we encoded them as dummy variables. After converting our numerical values the amount of variables changed to 29 in total, due to the dummy variables increasing the amount. We discussed utilizing a Principal Component Analysis, we will abreviate it to PCA from here on out, to deal with the increase as we can utilize this method for dimension reduction. However, after further consideration we realized utilizing a PCA to reduce the dimensions is inherently flawed as the binary variables and are not true continous variables like those needed for the PCA to be fully effective. We also realize we have `r nrow(data)` for `r ncol(data)`, so we do not think this level of dimensionality would cause serious problems. 

